#pragma once

#define ALLOC_ALL_MEMORY_VALUE 0

#define INVALID_FILE_HANDLE INVALID_HANDLE_VALUE
#define INVALID_FILE_MAPPING_HANDLE NULL
#define INVALID_FILE_VIEW_ADDR NULL

#define ELEMENT_NOT_FOUND_VALUE NULL