#pragma once

#define ALLOC_ALL_MEMORY_VALUE 0

#define INVALID_FILE_HANDLE INVALID_HANDLE_VALUE
#define INVALID_FILE_MAPPING_HANDLE NULL
#define INVALID_FILE_VIEW_ADDR NULL

#define FILEPATH_SIZE 512
#define USERS_GROUP_NAME_SIZE 512
#define USER_NAME_SIZE 256
#define USER_PASSWORD_SIZE 256

#define ELEMENT_NOT_FOUND_VALUE NULL

#define CREATE_MUTEX_ERROR "CreateMutexA error"